server:
  port: 8080
---
spring:
  cloud:
    gateway:
      routes:
        - id: user-svc-with-auth
          uri: ${USER_SVC}
          filters: JwtValidateFilter
          predicates:
            - Path=/api/users/**
            - Header=Authorization
        - id: user-svc
          uri: ${USER_SVC}
          predicates:
            - Path=/api/users/**

        - id: challenge-svc-with-auth
          uri: ${CHALLENGE_SVC}
          filters: JwtValidateFilter
          predicates:
            - Path=/api/challenges/**
            - Header=Authorization
        - id: challenge-svc
          uri: ${CHALLENGE_SVC}
          predicates:
            - Path=/api/challenges/**

        - id: problem-svc-with-auth
          uri: ${PROBLEM_SVC}
          filters: JwtValidateFilter
          predicates:
            - Path=/api/problems/**
            - Header=Authorization
        - id: problem-svc
          uri: ${PROBLEM_SVC}
          predicates:
            - Path=/api/problems/**

        - id: problem-catalog-svc-with-auth
          uri: ${CATALOG_SVC}
          filters: JwtValidateFilter
          predicates:
            - Path=/api/problem_catalogs/**
            - Header=Authorization
        - id: problem-catalog-svc
          uri: ${CATALOG_SVC}
          predicates:
            - Path=/api/problem_catalogs/**
jwt:
  secret: ${JWT.SECRET}
  issuer: ${JWT.ISSUER}